name: 'Flutter Setup'
description: 'Sets up Flutter environment with Firebase configuration'
inputs:
  firebase-options:
    description: 'Firebase options for configuration'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache Flutter and Dart dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ~/.flutter
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    
    - name: Disable cli animation and analytics
      shell: bash
      run: |
        flutter config --no-cli-animations
        flutter config --no-analytics
    
    - name: Configure firebase options
      shell: bash
      run: echo "${{ inputs.firebase-options }}" > ./lib/firebase_options.dart
