name: Flutter Checks
on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - '**/*.dart'

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  flutter-check:
    name: Flutter Checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true
          cache-key: true
      
      - name: Disable cli animation and analytics
        shell: bash
        run: |
          flutter config --no-cli-animations
          flutter config --no-analytics

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup firebase tools
        shell: bash
        run: sudo npm install -g firebase-tools
      
      - name: Configure firebase options
        shell: bash
        run: |
          dart pub global activate flutterfire_cli 1.0.1-dev.4
          flutterfire configure -p authentication-699e4 --android-package-name=com.codeTrenchers.evBookingOperators --platforms="android" --yes --token=${{ secrets.FIREBASE_TOKEN }}
      
      - name: Dart Format Check
        run: dart format --output=none $(find . -name "*.dart" ! -path "./lib/firebase_options.dart") --set-exit-if-changed
      
      - name: Flutter Analyze
        run: flutter analyze
