name: APK Release

on:
  workflow_dispatch:

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
    
      - name: Cache Flutter and Dart dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache Flutter Build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Firebase-cli
        run: curl -sL https://firebase.tools | bash

      - name: Install Flutterfire-cli
        run: flutter pub global activate flutterfire_cli 1.0.1-dev.4
      
      - name: Configure Flutterfire
        run: flutterfire configure --token ${{ secrets.FIREBASE_TOKEN }} -f -p authentication-699e4 -y --platforms android -a com.codeTrenchers.evBookingOperators

      - name: Flutter Build
        run: flutter build apk --release
